version: 2
jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     # build the application image
     - type: deploy
       name: "Publish on release tags"
       command: |
         set -eu
         TAG=$(git describe --tags)
         if [[ $TAG =~ ^[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$ ]]; then
           docker build -t deissh/avagen:$TAG .
           docker push deissh/avagen:$TAG
         fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: master
