version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/deissh/avagen
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go get -insecure ./...
      - run: go build -v
      - run: go fmt ./...
      - run: go vet ./...
      - run: go test -v ./...

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

  deploy:
    machine: true
    steps:
     - checkout
     - run: docker build -t deissh/avagen:$CIRCLE_SHA1 .
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - type: shell
       name: Build docker image
       command: |
         if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
         then
           version=$(git log -1 --pretty=%B)
           docker tag deissh/avagen:$CIRCLE_SHA1 deissh/avagen:$version
           docker push deissh/avagen:$version
         else
           echo "Not a release, skipping build"
         fi

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
