version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_dirictory: ~/repo

    steps:
      - checkout
      - run:
        name: run build
        command: |
          go get -insecure ./...
          go build -v
      - run:
        name: run tests
        command: |
          go fmt ./...
          go vet ./...
          go test -v ./...

  deploy:
    machine: true
    steps:
     - checkout
     - run: docker build -t deissh/avagen:$CIRCLE_SHA1 .
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker tag deissh/avagen:$CIRCLE_SHA1 deissh/avagen:$CIRCLE_TAG
     - run: docker push deissh/avagen:$CIRCLE_TAG

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
